spring:
  profiles:
    active: dev
  resources:
    cache-period: 604800
    chain:
      gzipped: true
      cache: true
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  thymeleaf:
    mode: LEGACYHTML5

# 端口
server:
  port: 80

ipip:
  download-url: https://user.ipip.net/download.php?type=ipdb&lang=CN&token=***********************
  path: /data/app/iplocation
  file-name: ipip.ipdb